//! Input event types — keyboard, mouse, scroll.

// Most variants are dispatch-only: constructed by producers or matched as no-op placeholders.
#[allow(dead_code)] // full event surface; several variants await producer wiring
pub enum Event {
    Key(u8),
    MouseClick(i32, i32),
    MouseMiddle(i32, i32),
    MouseRight(i32, i32),
    MouseDrag(i32, i32),
    MouseRelease,
    Scroll(i8),
    NotificationAdded(u64),
    NotificationRemoved(u64),
    ClipboardChanged,
    SessionChanged,
    PowerRequest(u8),
    AppStarted(u64),
    AppClosed(u64),
    AppFocused(u64),
    AppCrashed(u64),
    SettingsChanged,
    FocusChanged(u32),
    ElementActivated(u32),
    ThemeChanged,
    TooltipOpened,
    TooltipClosed,
    AppInstalled(u64),
    AppRemoved(u64),
    PermissionGranted(u64),
    PermissionDenied(u64),
    IPCConnected(u64),
    IPCDisconnected(u64),
    ServiceRegistered(&'static str),
    ServiceUnavailable(&'static str),
    FocusNext,
    FocusPrev,
}
