//! Configuration file management
//!
//! Provides functionality for reading and writing configuration files.

use crate::fs;
use alloc::string::String;
use alloc::string::ToString;
use alloc::vec::Vec;

/// Configuration key-value pair
#[derive(Debug, Clone)]
pub struct ConfigEntry {
    pub key: String,
    pub value: String,
}

/// Configuration file handler
pub struct Config {
    pub path: String,
    pub entries: Vec<ConfigEntry>,
}

impl Config {
    /// Load configuration from a file
    pub fn load(path: &str) -> Result<Self, i64> {
        let content = fs::read_to_string(path)?;
        let mut entries = Vec::new();

        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }

            if let Some(pos) = line.find('=') {
                let key = line[..pos].trim().to_string();
                let value = line[pos + 1..].trim().to_string();
                entries.push(ConfigEntry { key, value });
            }
        }

        Ok(Config {
            path: path.to_string(),
            entries,
        })
    }

    /// Create a new empty configuration
    pub fn new(path: &str) -> Self {
        Config {
            path: path.to_string(),
            entries: Vec::new(),
        }
    }

    /// Get a string value by key
    pub fn get_string(&self, key: &str) -> Option<&str> {
        for entry in &self.entries {
            if entry.key == key {
                return Some(&entry.value);
            }
        }
        None
    }

    /// Get a string value with default
    pub fn get_string_or(&self, key: &str, default: &str) -> String {
        self.get_string(key).unwrap_or(default).to_string()
    }

    /// Get a u32 value by key
    pub fn get_u32(&self, key: &str) -> Option<u32> {
        self.get_string(key)?.parse().ok()
    }

    /// Get a u32 value with default
    pub fn get_u32_or(&self, key: &str, default: u32) -> u32 {
        self.get_u32(key).unwrap_or(default)
    }

    /// Set a value
    pub fn set(&mut self, key: &str, value: &str) {
        // Update existing or add new
        for entry in &mut self.entries {
            if entry.key == key {
                entry.value = value.to_string();
                return;
            }
        }
        self.entries.push(ConfigEntry {
            key: key.to_string(),
            value: value.to_string(),
        });
    }

    /// Save configuration to file
    pub fn save(&self) -> Result<(), i64> {
        let mut content = String::new();
        content.push_str("# SkyOS Settings Configuration\n");
        content.push_str("# Generated by sargasettings\n\n");

        for entry in &self.entries {
            content.push_str(&entry.key);
            content.push_str("=");
            content.push_str(&entry.value);
            content.push_str("\n");
        }

        fs::write_file(&self.path, &content)
    }
}
